const images = [
  {
    id: "0",
    path: "/Images/Photographs/Animal1.jpg",
    category: "ANIMALS",
    description: "Prescription : Vitamin Sea",
    location: "San Diego, CA",
  },
  {
    id: "1",
    path: "/Images/Photographs/Animal2.jpg",
    category: "ANIMALS",
    description: "Sealiously cute",
    location: "San Diego, CA",
  },
  {
    id: "2",
    path: "/Images/Photographs/City1.jpg",
    category: "CITY",
    description: "Spotlight to the City lights",
    location: "Dallas, TX",
  },
  {
    id: "3",
    path: "/Images/Photographs/City2.jpg",
    category: "CITY",
    description: "The sky's the limit at Reunion Tower",
    location: "Dallas, TX",
  },
  {
    id: "4",
    path: "/Images/Photographs/Food.jpg",
    category: "FOOD",
    description: "How festive this bowl looks!",
    location: "Fort-Worth, TX",
  },
  {
    id: "5",
    path: "/Images/Photographs/Nature1.jpg",
    category: "NATURE",
    description: "Into the Woods",
    location: "Bellingham, WA",
  },
  {
    id: "6",
    path: "/Images/Photographs/Nature2.jpg",
    category: "NATURE",
    description: "Somewhere on the Journey",
    location: "Samish Bay, WA",
  },
  {
    id: "7",
    path: "/Images/Photographs/Nature3.jpg",
    category: "NATURE",
    description: "Start where you are \n Use What you have\n Do what you can!",
    location: "Seattle, WA",
  },
  {
    id: "8",
    path: "/Images/Photographs/other.jpg",
    category: "OTHER",
    description: "Geometry",
    location: "Fort-Worth, TX",
  },
  {
    id: "9",
    path: "/Images/Photographs/Other1.jpg",
    category: "OTHER",
    description: "Carousel",
    location: "Seattle, WA",
  },
  {
    id: "10",
    path: "/Images/Photographs/Portrait1.jpg",
    category: "PORTRAIT",
    description: "Getting ahead",
    location: "Seattle, WA",
  },
  {
    id: "11",
    path: "/Images/Photographs/Portrait2.jpg",
    category: "PORTRAIT",
    description: "Eyes on the Stars",
    location: "Seattle, WA",
  },
  {
    id: "12",
    path: "/Images/Photographs/Portrait3.jpg",
    category: "PORTRAIT",
    description: "Growth",
    location: "Seattle, WA",
  },
  {
    id: "13",
    path: "/Images/Photographs/Vehicle1.jpg",
    category: "VEHICLE",
    description: "1100 Classic Coffman",
    location: "Tempe, AZ",
  },
  {
    id: "14",
    path: "/Images/Photographs/Vehicle2.jpg",
    category: "VEHICLE",
    description: "Grand Theft Auto",
    location: "Los Angeles, CA",
  },
]

export { images }
