const images = [
  {
    id: "0",
    path: "/Images/Photographs/Animal1.jpg",
    category: "ANIMALS",
    description: "Prescription : Vitamin Sea",
    location: "San Diego, CA",
    price: "$120,00",
    quantity: "20",
    color: "#43272c",
  },
  {
    id: "1",
    path: "/Images/Photographs/Animal2.jpg",
    category: "ANIMALS",
    description: "Sealiously cute",
    location: "San Diego, CA",
    price: "$150,00",
    quantity: "30",
    color: "#195245",
  },
  {
    id: "2",
    path: "/Images/Photographs/City1.jpg",
    category: "CITY",
    description: "Spotlight to the City lights",
    location: "Dallas, TX",
    price: "$200,00",
    quantity: "25",
    color: "#06384b",
  },
  {
    id: "3",
    path: "/Images/Photographs/City2.jpg",
    category: "CITY",
    description: "The sky's the limit at Reunion Tower",
    location: "Dallas, TX",
    price: "$160,00",
    quantity: "20",
    color: "#ababab",
  },
  {
    id: "4",
    path: "/Images/Photographs/Food.jpg",
    category: "FOOD",
    description: "How festive this bowl looks!",
    location: "Fort-Worth, TX",
    price: "$80,00",
    quantity: "50",
    color: "#023473",
  },
  {
    id: "5",
    path: "/Images/Photographs/Nature1.jpg",
    category: "NATURE",
    description: "Into the Woods",
    location: "Bellingham, WA",
    price: "$320,00",
    quantity: "10",
    color: "#2d2d2d",
  },
  {
    id: "6",
    path: "/Images/Photographs/Nature2.jpg",
    category: "NATURE",
    description: "Somewhere on the Journey",
    location: "Samish Bay, WA",
    price: "$120,00",
    quantity: "20",
    color: "#f7eb01",
  },
  {
    id: "7",
    path: "/Images/Photographs/Nature3.jpg",
    category: "NATURE",
    description: "Start where you are \n Use What you have\n Do what you can!",
    location: "Seattle, WA",
    price: "$100,00",
    quantity: "30",
    color: "#e49003",
  },
  {
    id: "8",
    path: "/Images/Photographs/other.jpg",
    category: "OTHER",
    description: "Geometry",
    location: "Fort-Worth, TX",
    price: "$150,00",
    quantity: "15",
    color: "#1fd3f8",
  },
  {
    id: "9",
    path: "/Images/Photographs/Other1.jpg",
    category: "OTHER",
    description: "Carousel",
    location: "Seattle, WA",
    price: "$200,00",
    quantity: "60",
    color: "#140970",
  },
  {
    id: "10",
    path: "/Images/Photographs/Portrait1.jpg",
    category: "PORTRAIT",
    description: "Getting ahead",
    location: "Seattle, WA",
    price: "$130,00",
    quantity: "20",
    color: "#f45640",
  },
  {
    id: "11",
    path: "/Images/Photographs/Portrait2.jpg",
    category: "PORTRAIT",
    description: "Eyes on the Stars",
    location: "Seattle, WA",
    price: "$170,00",
    quantity: "35",
    color: "#005b63",
  },
  {
    id: "12",
    path: "/Images/Photographs/Portrait3.jpg",
    category: "PORTRAIT",
    description: "Growth",
    location: "Seattle, WA",
    price: "$190,00",
    quantity: "10",
    color: "#dbd7d1",
  },
  {
    id: "13",
    path: "/Images/Photographs/Vehicle1.jpg",
    category: "VEHICLE",
    description: "1100 Classic Coffman",
    location: "Tempe, AZ",
    price: "$220,00",
    quantity: "30",
    color: "#1AD0F6",
  },
  {
    id: "14",
    path: "/Images/Photographs/Vehicle2.jpg",
    category: "VEHICLE",
    description: "Grand Theft Auto",
    location: "Los Angeles, CA",
    price: "$60,00",
    quantity: "50",
    color: "#0a0048",
  },
]

// const colors = [
//   // "#43272c",
//   // "#195245",
//   // "#06384b",
//   // "#ababab",
//   // "#023473",
//   // "#2d2d2d",
//   // "#f7eb01",
//   // "#e49003",
//   // "#1fd3f8",
//   // "#140970",
//   // "#f45640",
//   // "#005b63",
//   // "#dbd7d1",
// ]
export { images }
